Repository woorifisa-service-dev-4th/frontend-4th-jeosok-nohwa, pull requests merged in 2025-01, with the labels that each got.

#9 모달 컴포넌트 구현
  app/components/ui/modal/Modal.jsx
  app/components/ui/modal/modal.css
  app/page.js
  package-lock.json
  package.json
  public/image/jeosok-nohwa-logo.png
  tsconfig.json
Labels: ✨featrue✨

#11 충돌 문제 타입스크립트 삭제하는 것으로 해결
  package-lock.json
  package.json
  tsconfig.json
Labels: bug

#14 fix: 캘린더 세기뷰 비활성화
  app/components/MyCalendar.jsx
  app/styles/custom-calendar.css
Labels: ✨featrue✨

#19 타임라인 컴포넌트
  app/calendar/page.js
  app/calendar/page.jsx
  app/components/timeline/Timeline.jsx
  app/components/timeline/TimelineItem.jsx
  app/components/timeline/timeline.css
  app/styles/custom-calendar.css
  app/styles/default.css
  package.json
  public/image/random1.png
  public/image/random2.png
  public/image/random3.png
Labels: ✨featrue✨

#24 fix: 캘린더 모달 클릭 이벤트 에러 수정
  app/components/CalendarModal.jsx
  app/components/MyCalendar.jsx
Labels: ✨featrue✨

#26 fix: 캘린더, 캘린더 모달 컴포넌트 분리
  app/calendar-test/page.jsx
Labels: ✨featrue✨

#27 채팅을 동적으로 받아온다.
  app/chat/[date]/page.js
  app/chat/page.js
  app/home/page.jsx
  components/chat/ChatHeader.js
  components/chat/ChatInput.js
  components/chat/MessageList.js
  package-lock.json
  package.json
  tailwind.config.mjs
Labels: ✨featrue✨

#29 feat : 일별 타임라인데이터 불러오기
  app/calendar/page.js
  app/components/MyCalendar.jsx
  app/components/timeline/TimelineItem.jsx
  app/deletetimeline/page.jsx
  app/globals.css
  app/styles/custom-calendar.css
Labels: ✨featrue✨

#30 feat: 홈페이지 채팅 연결 생성
  app/components/common-header.jsx
Labels: ✨featrue✨

#33 fix : props수정및 gif추가
  app/calendar/page.js
  app/components/timeline/Timeline.jsx
  app/components/timeline/TimelineItem.jsx
  public/image/giphy.gif
Labels: wontfix

#34 feat: 채팅에 캘린더 컴포넌트 적용
  app/calendar-test/page.jsx
  app/components/CalendarModal.jsx
  app/components/common-header.jsx
  components/chat/ChatHeader.js
Labels: ✨featrue✨

#36 실시간 채팅을 위한 Supabase 클라이언트 설정
  app/calendar/page.js
  app/calendar/page.jsx
  app/chat/page.js
  app/components/CalendarModal.jsx
  app/components/MyCalendar.jsx
  app/components/common-header.jsx
  app/components/nav-bar.jsx
  app/components/timeline/Timeline.jsx
  app/components/timeline/TimelineItem.jsx
  app/components/timeline/timeline.css
  app/components/ui/modal/modal.css
  app/deletetimeline/page.jsx
  app/globals.css
  app/layout.js
  app/styles/custom-calendar-modal.css
  app/styles/custom-calendar.css
  app/styles/default.css
  components/chat/ChatHeader.js
  components/chat/ChatInput.js
  components/chat/MessageList.js
  lib/supabaseClient.js
  package-lock.json
  package.json
  public/image/giphy.gif
  public/image/random1.png
  public/image/random2.png
  public/image/random3.png
Labels: ✨featrue✨

#40 선택한 날짜 기준으로 채팅 날짜 저장하도록 수정
  app/chat/page.js
Labels: 🔥fix🔥

#42 달력 폰트, 비율 변경
  app/globals.css
  app/styles/custom-calendar.css
  components/chat/ChatHeader.js
Labels: ✨featrue✨

#43 채팅 달력에서 선택 시 데이터 보이도록 수정
  app/chat/page.js
  components/chat/ChatHeader.js
Labels: 🔥fix🔥

#47 시간 저장 시 한국 시간으로 저장하도록 변경
  app/chat/page.js
Labels: 🔥fix🔥

#52 f전송 후에 textarea에 마지막 한 글자 남는 문제 해결
  components/chat/ChatInput.js
Labels: 🔥fix🔥

#55 날짜 하드코딩된 문제 해결
  app/chat/page.js
Labels: 🔥fix🔥

#56 46 feature timeline dbconnect
  app/components/timeline/Timeline.jsx
  app/components/timeline/TimelineItem.jsx
  app/components/ui/modal/modal.css
  app/home/page.jsx
Labels: ✨featrue✨

#58 feat: 캘린더 마킹 생성
  app/components/MyCalendar.jsx
  app/styles/custom-calendar.css
Labels: ✨featrue✨

#62 chat GPT 연결
  app/api/chat/route.js
  app/chat/page.js
  components/chat/ChatInput.js
  components/chat/MessageList.js
  package-lock.json
  package.json
Labels: ✨featrue✨

#66 채팅 요약 기능 추가
  app/api/chat/route.js
  app/api/chat/summarize/route.js
  app/chat/page.js
  components/chat/ChatInput.js
  components/chat/MessageList.js
  components/chat/SummarizeButton.js
Labels: ✨featrue✨

#67 배포 버전에 반영
  app/api/chat/route.js
  app/api/chat/summarize/route.js
  app/calendar/page.js
  app/chat/page.js
  app/components/MyCalendar.jsx
  app/components/common-header.jsx
  app/components/timeline/Timeline.jsx
  app/deletetimeline/page.jsx
  app/globals.css
  app/home/page.jsx
  app/layout.js
  app/notifications/page.js
  app/profile/page.jsx
  app/ranking/page.jsx
  app/timeline/page.js
  components/calendar/CalendarModal.jsx
  components/calendar/MyCalendar.jsx
  components/calendar/styles/custom-calendar-modal.css
  components/calendar/styles/custom-calendar.css
  components/calendar/styles/default.css
  components/chat/ChatHeader.js
  components/chat/ChatInput.js
  components/chat/MessageList.js
  components/chat/SummarizeButton.js
  components/chat/styles/CustomScrollBar.css
  components/common/ClientViewportHandler.js
  components/common/CommonHeader.jsx
  components/common/Modal.jsx
  components/common/NavBar.jsx
  components/common/styles/modal.css
  components/home/SkeletonLoader.js
  components/timeline/Timeline.jsx
  components/timeline/TimelineItem.jsx
  components/timeline/TimelineSkeleton.js
  components/timeline/styles/timeline.css
  package-lock.json
  package.json
Labels: 💫 deploy💫 

#69 대화 저장 오류 수정
  app/chat/page.js
  components/chat/ChatInput.js
Labels: 🔥fix🔥

#70 요약을 제목과 긴 요약으로 나누어 요청
  app/api/chat/summarize/route.js
  components/chat/MessageList.js
  components/chat/SummarizeButton.js
Labels: 🔥fix🔥

#71 feat :타임라인 요약내용 모달
  app/home/page.jsx
  components/common/Modal.jsx
  components/common/styles/modal.css
  components/timeline/Timeline.jsx
  package-lock.json
  package.json
Labels: ✨featrue✨

#72 달력, 타임라인 스타일 및 정렬 수정
  app/home/page.jsx
  app/notifications/page.js
  app/profile/page.jsx
  app/ranking/page.jsx
  app/timeline/page.js
  components/calendar/MyCalendar.jsx
  components/calendar/styles/custom-calendar.css
  components/common/CommonHeader.jsx
  components/timeline/Timeline.jsx
  components/timeline/TimelineItem.jsx
Labels: ✨featrue✨, 🔥fix🔥

#73 배포 버전에 반영
  app/api/chat/summarize/route.js
  app/chat/page.js
  app/home/page.jsx
  app/notifications/page.js
  app/profile/page.jsx
  app/ranking/page.jsx
  app/timeline/page.js
  components/calendar/MyCalendar.jsx
  components/calendar/styles/custom-calendar.css
  components/chat/ChatInput.js
  components/chat/MessageList.js
  components/chat/SummarizeButton.js
  components/common/CommonHeader.jsx
  components/common/Modal.jsx
  components/common/styles/modal.css
  components/timeline/Timeline.jsx
  components/timeline/TimelineItem.jsx
  package-lock.json
  package.json
Labels: 💫 deploy💫 

#75 메인 페이지 구현
  app/globals.css
  app/page.js
  components/main/RouterButton.jsx
  package-lock.json
Labels: ✨featrue✨
