Repository woorifisa-service-dev-4th/frontend-4th-jeosok-nohwa, pull requests merged in 2025-02, with the labels that each got.

#77 공통 헤더를 전역 layout에서 분리
  app/chat/page.js
  app/home/page.jsx
  app/layout.js
  app/profile/page.jsx
  app/ranking/page.jsx
  app/timeline/page.js
Labels: 🔧refactor🔧

#78 클라이언트에서 DB조회하는 것을 api로 분리
  app/api/chat/route.js
  app/api/chat/summarize/route.js
  app/api/events/route.js
  app/api/marked-dates/route.js
  app/api/messages/route.js
  app/api/summaries/route.js
  app/chat/page.js
  app/globals.css
  app/home/page.jsx
  app/layout.js
  app/page.js
  app/profile/page.jsx
  app/ranking/page.jsx
  app/timeline/page.js
  components/calendar/MyCalendar.jsx
  components/chat/SummarizeButton.js
  components/common/CommonHeader.jsx
  components/main/RouterButton.jsx
  components/timeline/TimelineItem.jsx
  lib/supabase.js
  lib/supabaseClient.js
  package-lock.json
Labels: 🔥fix🔥

#79 로고 디자인 적용
  app/api/chat/route.js
  app/api/chat/summarize/route.js
  app/api/events/route.js
  app/api/marked-dates/route.js
  app/api/messages/route.js
  app/api/summaries/route.js
  app/chat/page.js
  app/favicon.ico
  app/home/page.jsx
  app/timeline/page.js
  components/calendar/MyCalendar.jsx
  components/chat/SummarizeButton.js
  components/common/CommonHeader.jsx
  components/timeline/TimelineItem.jsx
  lib/supabase.js
  lib/supabaseClient.js
  public/image/jeosok-nohwa-logo.png
Labels: ✨featrue✨

#80 배포 버전에 반영
  app/favicon.ico
  public/image/jeosok-nohwa-logo.png
Labels: 💫 deploy💫 

#81 개발 버전에 수정
  app/chat/page.js
  app/page.js
  components/calendar/styles/custom-calendar.css
  components/main/RouterButton.jsx
  next.config.mjs
  public/image/jeosok-nohwa-logo.png
Labels: 🔥fix🔥

#90 57 feature calendar mark
  components/calendar/styles/custom-calendar.css
  components/calendar/styles/default.css
Labels: 🔥fix🔥
